Repository varun6996/pythonprograms, pull requests merged in 2020-10, with the labels that each got.

#3 Mr nevil patch 1
  README.md
  bubbleSort.py
Labels: hacktoberfest-accepted

#4 Create towerOfHanoi.py
  towerOfHanoi.py
Labels: hacktoberfest, hacktoberfest-accepted

#6 Create InsertionSort
  InsertionSort
Labels: enhancement, hacktoberfest-accepted

#5 Create BinarySearch
  BinarySearch
Labels: hacktoberfest, hacktoberfest-accepted

#7 Create MergeSort
  MergeSort
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 Create Random Password Generator using Tkinter
  Random Password Generator using Tkinter
Labels: hacktoberfest, hacktoberfest-accepted

#8 Created: Implementation of Quick Sort in Python
  quickSort.py
Labels: hacktoberfest-accepted

#9 Create TicTacToe
  TicTacToe
Labels: hacktoberfest, hacktoberfest-accepted

#10 Create TicTacToe with GUI
  TicTacToe with GUI
Labels: hacktoberfest, hacktoberfest-accepted

#12 Create FLAMES game using Tkinter
  FLAMES game using Tkinter
Labels: hacktoberfest, hacktoberfest-accepted

#11 Create Number Guessing Game
  Number Guessing Game
Labels: hacktoberfest, hacktoberfest-accepted
